str='python  1231 312 holle ddd  py'
str_2='py'
#________________________
#find
str.find(str_2)
print(str)
#------------------------
#index
str.index(str_2)
print(str)
#________________________
#count
str.count(str_2)
print(str)
#------------------------
#replace
str.replace(str,'abcd',1)
print(str)
#________________________
#split
str.split(' ',2)
print(str)
#------------------------
#isalpha
str.isalpha()
print(str)
#------------------------
#isdigit
str.isdigit()
print(str)
#------------------------
#isnum
str.isalnum()
print(str)
#------------------------
#isspace
str.isspace()
print(str)
