str='        I love china ddd   '
#_________________________
#capitlize
print(str.capitalize())
#_________________________
#title
print(str.title())
#_________________________
#startwith
print(str.startswith('herry'))
#_________________________
#lower
print(str.lower())
#_________________________
#upper
print(str.upper())
#_________________________
#ljust
print(str.ljust(5))
#_________________________
#rjust
print(str.rjust(5))
#_________________________
#center
print(str.center(5))
#_________________________
#join
print(str.join('-'))
#_________________________
#lstrip
print(str.lstrip())
#_________________________
#rstrip
print(str.rstrip())